// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pagila.API.Models;

[Table("actor")]
[Index("LastName", Name = "idx_actor_last_name")]
public partial class Actor
{
    [Key]
    [Column("actor_id")]
    public int ActorId { get; set; }

    [Required]
    [Column("first_name")]
    public string FirstName { get; set; }

    [Required]
    [Column("last_name")]
    public string LastName { get; set; }

    [Column("last_update")]
    public DateTime LastUpdate { get; set; }

    [InverseProperty("Actor")]
    public virtual ICollection<FilmActor> FilmActors { get; set; } = new List<FilmActor>();
}