// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pagila.API.Models;

[Table("address")]
[Index("CityId", Name = "idx_fk_city_id")]
public partial class Address
{
    [Key]
    [Column("address_id")]
    public int AddressId { get; set; }

    [Required]
    [Column("address")]
    public string Address1 { get; set; }

    [Column("address2")]
    public string Address2 { get; set; }

    [Required]
    [Column("district")]
    public string District { get; set; }

    [Column("city_id")]
    public int CityId { get; set; }

    [Column("postal_code")]
    public string PostalCode { get; set; }

    [Required]
    [Column("phone")]
    public string Phone { get; set; }

    [Column("last_update")]
    public DateTime LastUpdate { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("Addresses")]
    public virtual City City { get; set; }

    [InverseProperty("Address")]
    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    [InverseProperty("Address")]
    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();

    [InverseProperty("Address")]
    public virtual ICollection<Store> Stores { get; set; } = new List<Store>();
}