// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NpgsqlTypes;

namespace Pagila.API.Models;

[Table("film")]
[Index("LanguageId", Name = "idx_fk_language_id")]
[Index("OriginalLanguageId", Name = "idx_fk_original_language_id")]
[Index("Title", Name = "idx_title")]
public partial class Film
{
    [Key]
    [Column("film_id")]
    public int FilmId { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("release_year")]
    public int? ReleaseYear { get; set; }

    [Column("language_id")]
    public int LanguageId { get; set; }

    [Column("original_language_id")]
    public int? OriginalLanguageId { get; set; }

    [Column("rental_duration")]
    public short RentalDuration { get; set; }

    [Column("rental_rate")]
    [Precision(4, 2)]
    public decimal RentalRate { get; set; }

    [Column("length")]
    public short? Length { get; set; }

    [Column("replacement_cost")]
    [Precision(5, 2)]
    public decimal ReplacementCost { get; set; }

    [Column("last_update")]
    public DateTime LastUpdate { get; set; }

    [Column("special_features")]
    public List<string> SpecialFeatures { get; set; }

    [Required]
    [Column("fulltext")]
    public NpgsqlTsVector Fulltext { get; set; }

    [InverseProperty("Film")]
    public virtual ICollection<FilmActor> FilmActors { get; set; } = new List<FilmActor>();

    [InverseProperty("Film")]
    public virtual ICollection<FilmCategory> FilmCategories { get; set; } = new List<FilmCategory>();

    [InverseProperty("Film")]
    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    [ForeignKey("LanguageId")]
    [InverseProperty("FilmLanguages")]
    public virtual Language Language { get; set; }

    [ForeignKey("OriginalLanguageId")]
    [InverseProperty("FilmOriginalLanguages")]
    public virtual Language OriginalLanguage { get; set; }
}