// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pagila.API.Models;

[Table("language")]
public partial class Language
{
    [Key]
    [Column("language_id")]
    public int LanguageId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(20)]
    public string Name { get; set; }

    [Column("last_update")]
    public DateTime LastUpdate { get; set; }

    [InverseProperty("Language")]
    public virtual ICollection<Film> FilmLanguages { get; set; } = new List<Film>();

    [InverseProperty("OriginalLanguage")]
    public virtual ICollection<Film> FilmOriginalLanguages { get; set; } = new List<Film>();
}