// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pagila.API.Models;

[Keyless]
public partial class NicerButSlowerFilmList
{
    [Column("fid")]
    public int? Fid { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("category")]
    public string Category { get; set; }

    [Column("price")]
    [Precision(4, 2)]
    public decimal? Price { get; set; }

    [Column("length")]
    public short? Length { get; set; }

    [Column("actors")]
    public string Actors { get; set; }
}