// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pagila.API.Models;

[PrimaryKey("PaymentDate", "PaymentId")]
[Table("payment_p2022_04")]
[Index("CustomerId", Name = "idx_fk_payment_p2022_04_customer_id")]
[Index("StaffId", Name = "idx_fk_payment_p2022_04_staff_id")]
[Index("CustomerId", Name = "payment_p2022_04_customer_id_idx")]
public partial class PaymentP202204
{
    [Key]
    [Column("payment_id")]
    public int PaymentId { get; set; }

    [Column("customer_id")]
    public int CustomerId { get; set; }

    [Column("staff_id")]
    public int StaffId { get; set; }

    [Column("rental_id")]
    public int RentalId { get; set; }

    [Column("amount")]
    [Precision(5, 2)]
    public decimal Amount { get; set; }

    [Key]
    [Column("payment_date")]
    public DateTime PaymentDate { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("PaymentP202204s")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("RentalId")]
    [InverseProperty("PaymentP202204s")]
    public virtual Rental Rental { get; set; }

    [ForeignKey("StaffId")]
    [InverseProperty("PaymentP202204s")]
    public virtual Staff Staff { get; set; }
}