// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pagila.API.Models;

[Keyless]
public partial class StaffList
{
    [Column("id")]
    public int? Id { get; set; }

    [Column("name")]
    public string Name { get; set; }

    [Column("address")]
    public string Address { get; set; }

    [Column("zip code")]
    public string ZipCode { get; set; }

    [Column("phone")]
    public string Phone { get; set; }

    [Column("city")]
    public string City { get; set; }

    [Column("country")]
    public string Country { get; set; }

    [Column("sid")]
    public int? Sid { get; set; }
}