// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pagila.API.Models;

[Table("staff")]
public partial class Staff
{
    [Key]
    [Column("staff_id")]
    public int StaffId { get; set; }

    [Required]
    [Column("first_name")]
    public string FirstName { get; set; }

    [Required]
    [Column("last_name")]
    public string LastName { get; set; }

    [Column("address_id")]
    public int AddressId { get; set; }

    [Column("email")]
    public string Email { get; set; }

    [Column("store_id")]
    public int StoreId { get; set; }

    [Column("active")]
    public bool Active { get; set; }

    [Required]
    [Column("username")]
    public string Username { get; set; }

    [Column("password")]
    public string Password { get; set; }

    [Column("last_update")]
    public DateTime LastUpdate { get; set; }

    [Column("picture")]
    public byte[] Picture { get; set; }

    [ForeignKey("AddressId")]
    [InverseProperty("Staff")]
    public virtual Address Address { get; set; }

    [InverseProperty("Staff")]
    public virtual ICollection<PaymentP202201> PaymentP202201s { get; set; } = new List<PaymentP202201>();

    [InverseProperty("Staff")]
    public virtual ICollection<PaymentP202202> PaymentP202202s { get; set; } = new List<PaymentP202202>();

    [InverseProperty("Staff")]
    public virtual ICollection<PaymentP202203> PaymentP202203s { get; set; } = new List<PaymentP202203>();

    [InverseProperty("Staff")]
    public virtual ICollection<PaymentP202204> PaymentP202204s { get; set; } = new List<PaymentP202204>();

    [InverseProperty("Staff")]
    public virtual ICollection<PaymentP202205> PaymentP202205s { get; set; } = new List<PaymentP202205>();

    [InverseProperty("Staff")]
    public virtual ICollection<PaymentP202206> PaymentP202206s { get; set; } = new List<PaymentP202206>();

    [InverseProperty("Staff")]
    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();

    [ForeignKey("StoreId")]
    [InverseProperty("Staff")]
    public virtual Store Store { get; set; }
}