// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pagila.API.Models;

[Table("store")]
[Index("ManagerStaffId", Name = "idx_unq_manager_staff_id", IsUnique = true)]
public partial class Store
{
    [Key]
    [Column("store_id")]
    public int StoreId { get; set; }

    [Column("manager_staff_id")]
    public int ManagerStaffId { get; set; }

    [Column("address_id")]
    public int AddressId { get; set; }

    [Column("last_update")]
    public DateTime LastUpdate { get; set; }

    [ForeignKey("AddressId")]
    [InverseProperty("Stores")]
    public virtual Address Address { get; set; }

    [InverseProperty("Store")]
    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    [InverseProperty("Store")]
    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    [InverseProperty("Store")]
    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();
}